dataset: cifar10
net_type: resnet
depth: 50

epochs: 200
batch_size: 64
lr: 0.1
momentum: 0.9
weight_decay: 0.0005
schedule_steps: [100, 150]

experiment_name: cifar10_resnet50

cutmix:
  beta: 1.0
  prob: 1.0
  num: 1
